unit TestUnit1;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, System.SysUtils, Vcl.Graphics, Winapi.Windows, System.Variants,
  System.Classes, Vcl.Dialogs, Vcl.Controls, Vcl.Forms, Winapi.Messages, Unit1;

type
  // Test methods for class TForm1

  TestTForm1 = class(TTestCase)
  strict private
    FForm1: TCalculadora;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestSoma;
  end;

implementation




procedure TestTForm1.SetUp;
begin
  FForm1 := TCalculadora.Create();

end;

procedure TestTForm1.TearDown;
begin
  FForm1.Free;
end;

procedure TestTForm1.TestSoma;
var
  ReturnValue : Real;
  NumeroDois : Real;
  NumeroUm : Real;
  ValorEsperado: Real;

begin
  NumeroUm := 4;
  NumeroDois := 2;

  ValorEsperado:= 6;


  ReturnValue := TCalculadora.Soma(NumeroUm,NumeroDois );

  CheckEquals(ValorEsperado, ReturnValue);
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTForm1.Suite);
end.

